version: "3.9"

services:
  gatewayapi:
    container_name: gatewayapi
    build:
      context: ./src/GateWayApi
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
